@extends('farsar-backend.layout.dashboard')
@section('content')
    <div class="table">
        <table>
            <thead>
            <tr>
                <td>#</td>
                <td>عنوان</td>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>1</td>
                <td>تلخ</td>
            </tr>
            <tr>
                <td>2</td>
                <td>تلخ</td>
            </tr>
            <tr>
                <td>3</td>
                <td>تلخ</td>
            </tr>
            <tr>
                <td>4</td>
                <td>تلخ</td>
            </tr>
            </tbody>
        </table>
        <a href="#" class="jadid"></a>
    </div>
@endsection
